{
 "title": "Medusa Exporter Dashboard",
 "description": "Dashboard works with medusa_exporter",
 "tags": [
  "medusa",
  "cassandra",
  "backups"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(medusa_exporter_status,job)"
    }
   },
   {
    "name": "backup_type",
    "label": "Backup type",
    "query": {
     "query": "label_values(medusa_backup_info{job=~\"${job}\"},backup_type)"
    }
   },
   {
    "name": "backup_name",
    "label": "Backup name",
    "query": {
     "query": "label_values(medusa_backup_info{job=~\"${job}\", backup_type=~\"${backup_type}\"},backup_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backups CNT",
   "type": "stat",
   "description": "Number of all backups for selected jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (job) (medusa_backup_info{job=~\"${job}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full backups CNT",
   "type": "stat",
   "description": "Number of full backups for selected jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (job) (medusa_backup_info{job=~\"$job\", backup_type=\"full\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Differential backups CNT",
   "type": "stat",
   "description": "Number of differential backups for selected jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (job) (medusa_backup_info{job=~\"${job}\", backup_type=\"differential\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups CNT",
   "type": "timeseries",
   "description": "Number of backups for selected jobs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by (job) (medusa_backup_info{job=~\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Completed backups CNT",
   "type": "stat",
   "description": "Number of completed backups for selected jobs.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(medusa_backup_status{job=~\"${job}\"} == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incompleted backups CNT",
   "type": "stat",
   "description": "Number of Incompleted backups for selected jobs.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(medusa_backup_status{job=~\"${job}\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last successful backups",
   "type": "table",
   "description": "Last successful backups for selected jobs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "medusa_backup_since_last_completion_seconds{job=~\"${job}\"}"
    },
    {
     "expr": "medusa_backup_last_duration_seconds{job=~\"${job}\"}"
    },
    {
     "expr": "medusa_backup_last_objects{job=~\"${job}\"}"
    },
    {
     "expr": "medusa_backup_last_size_bytes{job=~\"${job}\"}"
    }
   ]
  },
  { "title": "General backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Average backup duration",
   "type": "timeseries",
   "description": "Average backup duration for jobs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job, backup_type) (medusa_backup_duration_seconds{job=~\"${job}\"})",
     "legendFormat": "{{job}} | {{backup_type}}"
    }
   ]
  },
  {
   "title": "Average size of backup",
   "type": "timeseries",
   "description": "Average size of backup for selected jobs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job, backup_type) (medusa_backup_size_bytes{job=~\"${job}\"})",
     "legendFormat": "{{job}} | {{backup_type}}"
    }
   ]
  },
  { "title": "Detailed backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Backup completion status",
   "type": "table",
   "description": "Backup completion status, objects in backup and size for selected backups.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "medusa_backup_status{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"${backup_name}\"}"
    },
    {
     "expr": "medusa_backup_objects{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"${backup_name}\"}"
    },
    {
     "expr": "medusa_backup_size_bytes{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"${backup_name}\"}"
    }
   ]
  },
  {
   "title": "Backup duration",
   "type": "table",
   "description": "Backup duration for selected backups.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "medusa_backup_duration_seconds{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"${backup_name}\"}"
    }
   ]
  },
  {
   "title": "Backup detail info",
   "type": "table",
   "description": "Backup detail info for selected backups.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "medusa_backup_info{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "medusa_backup_completed_nodes{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "medusa_backup_incomplete_nodes{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"$backup_name\"}"
    },
    {
     "expr": "medusa_backup_missing_nodes{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"$backup_name\"}"
    }
   ]
  },
  { "title": "Detailed node backups info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Node backup completion status",
   "type": "table",
   "description": "Node backup completion status, objects in node backup and size for selected backups.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "medusa_node_backup_status{job=~\"${job}\", backup_type=~\"${backup_type}\", backup_name=~\"${backup_name}\"}"
    },
    {
     "expr": "medusa_node_backup_objects{job=~\"${job}\", backup_type=~\"${backup_type}\", backup_name=~\"${backup_name}\"}"
    },
    {
     "expr": "medusa_node_backup_size_bytes{job=~\"${job}\", backup_type=~\"${backup_type}\", backup_name=~\"${backup_name}\"}"
    }
   ]
  },
  {
   "title": "Node backup duration",
   "type": "table",
   "description": "Node backup duration for selected backups.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "medusa_node_backup_duration_seconds{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"${backup_name}\"}"
    }
   ]
  },
  {
   "title": "Node backup detail info",
   "type": "table",
   "description": "Node backup detail info for selected backups.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "medusa_node_backup_info{job=~\"${job}\", backup_type=~\"${backup_type}\",backup_name=~\"$backup_name\"}"
    }
   ]
  },
  { "title": "Medusa Exporter info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Exporter status and build info",
   "type": "table",
   "description": "Information about exporter build parameters and status of getting data from  Medusa.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "targets": [
    { "expr": "medusa_exporter_build_info", "legendFormat": "__auto" },
    { "expr": "medusa_exporter_status", "legendFormat": "__auto" }
   ]
  }
 ]
}